blank_issues_enabled: false
contact_links:
  - name: 💬 Fragen & Diskussion
    url: https://github.com/ebcFlagman/gymboard/discussions
    about: Für allgemeine Fragen bitte die Discussions nutzen statt ein Issue zu eröffnen.
